### PR TITLE
#105, display conflation settings and statistics in the UI

### PR DESCRIPTION
**Pull request by brianhatchl**

### CODE REVIEW

**Comment by brianhatchl** [comment]
Josh, would you please review & merge?

**Comment by sisskind** [comment]
@brianhatchl Will do this evening.

**Comment by sisskind** [comment]
@brianhatchl Getting the following error when I try to open statistics pane: ```Uncaught TypeError: Object.assign is not a function```

**Comment by brianhatchl** [comment]
What browser & version are you using?

**Comment by sisskind** [comment]
Google Chrome Version 43.0.2357.81 (64-bit)

**Comment by brianhatchl** [comment]
Ok, I tested in Firefox and Chromium.  Let me try Chrome.

**Comment by brianhatchl** [comment]
Hmm, seems to work in Chrome Version 48.0.2564.97 (64-bit)

**Comment by sisskind** [comment]
Can confirm it works in Firefox.  Will update Chrome version and test again.

**Comment by sisskind** [comment]
Confirm it works in that version of Chrome.
